### ISSUE TITLE
ccsniffpiper on linux

### ISSUE THREAD

**Issue by xeonphi** [andrewdodd/ccsniffpiper#6]
Hi!
I have try to run ccsniffer on ubuntu but get this error:

Traceback (most recent call last):
  File "./ccsniffpiper.py", line 549, in <module>
    snifferDev = CC2531(handlerDispatcher, args.channel)
  File "./ccsniffpiper.py", line 298, in __init__
    self.name = usb.util.get_string(self.dev, 256, 2) # get name from USB descriptor
  File "/usr/local/lib/python2.7/dist-packages/usb/util.py", line 328, in get_string
    raise ValueError("The device does not support the specified langid")
ValueError: The device does not support the specified langid

Do have any ideas how to fix this?

**Comment by gillesDD** [comment]
Hi,
is lsusb gives you the following for the 2531 ?:
Bus 002 Device 004: ID 0451:16ae Texas Instruments, Inc.


2015-07-10 13:36 GMT+02:00 xeonphi <notifications@github.com>:

**Comment by xeonphi** [comment]
I got this from lsusb:
Bus 007 Device 010: ID 0451:16ae Texas Instruments, Inc.

**Comment by gillesDD** [comment]
Well, your device is connected.
as far as I am concerned, I start ccs with sudo in my ubuntu VM and it works.

**Comment by andrewdodd** [comment]
Hi Guys,

To be honest, I haven't really touched this in a while. But plenty of people seem to be getting it to work.

I always used these tools with the CC2531EMK modules.

Unfortunately, I can't really help much here anyway, as I left the company I was doing this stuff for and don't have any CC2531EMKs in my possession.

Good luck!

**Comment by xeonphi** [comment]
thanks you for your quick answers.
GillesDD what version of python and ubuntu are you using?

**Comment by xeonphi** [comment]
I put a static value for the device description as a workaround. It seems that pyusb wasn't able to retrieve it directly from the device.
self.name = "TI CC2531" #usb.util.get_string(self.dev, 256, 2) # get name from USB descriptor

**Comment by XD-Andy** [comment]
Hi,

Old thread I know, but wanted to put my input in re macOS Sierra.

Thanks to XeonPhi's workaround, I've now got this working under MacOS.

Steps I had to go thru'

1: Install Homebrew (http://macappstore.org/libusb/)
2: Install Libusb (same url above)
3: Install python 2.7.13 (https://www.python.org/downloads/)
4: Install pyusb (from terminal 'sudo pip install pyusb'; PIP installed with python)
5: Download ccsniffpiper
6: Edit ccsniffpiper.py using IDLE (downloaded with python, in python application folder) to set static value as XeonPhi describes above
7: run ccsniffpiper via terminal; navigate to the ccsniffpiper folder via command line then enter 'sudo python ccsniffpiper' and press return
8: press 's' and return to start capture
9: open Wireshark
10: follow instructions on ccsniffpiper cover page here at GitHub, as provided by author, to set the IEEE802.15.4 protocol preferences and to point Wireshark at the 'pipe' from ccsniffpiper
11: start capture in Wireshark

**Comment by XD-Andy** [comment]
And ..... !

Have gotten it running in Kali Linux on a Raspberry Pi 3, doing pretty much the above, minus the 'homebrew' but needed to install python, libusb, python-pip, pyusb, and edit the ccsniffpiper.py file as XeonPhi suggests (which meant installing idle, which is not installed with python 2.7.13 .... but

need to launch Wireshark from terminal as follows

wireshark -k -i /tmp/ccsniffpiper &

Don;t know if 'sudo' is needed or not, but I've just done it with sudo.

**Comment by skandragon** [comment]
I also have the same issue.  Perhaps a try/catch block to set the default if it's not working?
